# Generated by Django 4.0.7 on 2022-08-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ParsedImages',
        ),
    ]
