# Generated by Django 4.0.7 on 2022-08-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_rename_images_parsedimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedimages',
            name='text_c',
            field=models.CharField(default='asd', max_length=255, verbose_name='Texto C'),
            preserve_default=False,
        ),
    ]
